Partly document bag sources and header
pret/pokeplatinum pull request #11
Opened 2023-05-16 19:19 UTC by LangeTreeDorpie

This is my first ever PR for an opensource project and also my first try on a reverse engineering project. 

But don't be gentle and shoot me 😄

2023-06-03 07:38 UTC, Nomura-RH requested changes
Hi! Sorry for taking this long to review, I have been busy these past weeks. This PR looks good, I left a couple comments about minor adjustments I'd like you to make, but great job overall! Contributions like these are greatly appreciated, and I hope you will do more in the future.

2023-06-03 07:38 UTC, Nomura-RH commented on include/struct_defs/struct_0207CDEC.h
>  typedef struct {
Structs must be typedef'd, and have the same name as the typedef, i.e.

`typedef struct ItemSlot {
    u16 unk_00;
    u16 unk_02;
} ItemSlot;`

2023-06-03 07:38 UTC, Nomura-RH commented on include/bag.h
> +#ifndef POKEPLATINUM_UNK_0207D3B8_H
You forgot to change the header guard :)

2023-06-03 07:38 UTC, Nomura-RH commented on include/bag.h
> +int bag(void);
Bag_sizeof

2023-10-26 01:00 UTC, PikalaxALT commented
Is this PR abandoned?

2024-06-20 01:21 UTC, lhearachel commented
Closing in favor of #229

2024-06-20 01:21 UTC, closed without merging