Update unk_0204CDDC.c with semantics
pret/pokeplatinum pull request #12
Opened 2023-06-14 04:01 UTC by patilise

Pretty much the same logic from pret/pokediamond/blob/master/arm9/src/scrcmd_amity_square.c

2023-06-14 13:18 UTC, luckytyphlosion requested changes

2023-06-14 13:18 UTC, luckytyphlosion commented on src/unk_0204CDDC.c
> +    u16 * ret_ptr = inline_0204FCAC(ctx);
`ret_ptr` -> `retPtr`

2023-07-05 08:10 UTC, lhearachel commented
Is there any extra info on what exactly these functions do? They look to me like they're related to accessories: https://github.com/pret/pokediamond/blob/master/arm9/src/scrcmd_amity_square.c#L10

2023-07-05 10:34 UTC, patilise commented
They are functions that determine items/accessories that your walking Pokémon picks up in Amity Square, and that a man in Amity Square gives.
Also refer to: https://bulbapedia.bulbagarden.net/wiki/Amity_Square

2023-10-26 00:59 UTC, PikalaxALT commented
Is this PR abandoned?

2023-10-26 19:54 UTC, merged