Label some code referenced by main
pret/pokeplatinum pull request #133
Opened 2024-01-28 21:40 UTC by meithecatte

2024-01-28 21:49 UTC, lhearachel requested changes

2024-01-28 21:49 UTC, lhearachel commented on include/functypes/funcptr_02017798.h
> +typedef void (* Callback)(void *);
Any chance we could move this into an appropriate header based on the usages?

```
$ grep -r 'functypes/funcptr_02017798.h' include/
include/core_sys.h:#include "functypes/funcptr_02017798.h"
include/unk_02017728.h:#include "functypes/funcptr_02017798.h"

$ grep -r 'functypes/funcptr_02017798.h' src/
src/unk_02017728.c:#include "functypes/funcptr_02017798.h"
```

2024-01-28 21:49 UTC, lhearachel commented on src/main.c
>              }
I'm wondering if this is the 30-FPS lock that the gen4 games are infamous for. That `OS_WaitIrq` call looks suspicious.

2024-01-28 21:49 UTC, lhearachel commented on include/core_sys.h
> +    void * hblankCallbackData;
Pull the names on these pointer-vars back a character.

```suggestion
    Callback mainCallback;
    void *mainCallbackData;
    Callback hblankCallback;
    void *hblankCallbackData;
```

2024-01-28 21:49 UTC, lhearachel commented on include/core_sys.h
> +    u32 * heapCanary;
Here, as well, as above.

```suggestion
    u32 *heapCanary;
```

2024-01-28 21:49 UTC, lhearachel commented on include/unk_02017728.h
> +BOOL SetHBlankCallback(Callback cb, void * data);
Here, as above.

```suggestion
void SetMainCallback(Callback cb, void *data);
void DisableHBlank(void);
BOOL SetHBlankCallback(Callback cb, void *data);
```

2024-01-29 19:57 UTC, meithecatte commented
Thank you for the suggestions. I applied them and rebased onto current `main`.

2024-01-29 20:14 UTC, lhearachel approved these changes

2024-01-29 20:14 UTC, merged