Add comments & definitions to map_header.h and map_header.c
pret/pokeplatinum pull request #163
Opened 2024-03-15 23:47 UTC by Mr-Toodguy

2024-03-16 04:01 UTC, lhearachel requested changes
This is a little hard to review due to the overall diff size of `map_headers.c`. Could we pull the `mapHeaders` table out into a separate file? e.g. `include/data/map_headers.h`, then include the file in `map_headers.c` to bring the total diff size down. While we're at it, let's update the name to be `sMapHeaders`.

2024-03-16 04:06 UTC, Mr-Toodguy commented
Ok sounds good, I agree that the giant table in map_headers.c is undesirable.

2024-03-17 05:08 UTC, lhearachel approved these changes
Love to see it.

2024-03-17 05:08 UTC, lhearachel commented on src/map_header.c
> +#include "data/map_headers.h"
:raised_hands:

2024-03-17 05:08 UTC, merged