Start Documenting Save Data
pret/pokeplatinum pull request #167
Opened 2024-03-23 19:57 UTC by ravepossum

This is a handful of documentation for save data, including:

- Naming the savedata .c and .h files
- Naming several savedata functions/struct members/variables
- Moving the save data structs to the header file and removing the struct declaration file for SaveData
- Creating a constants file for savedata.h and save_table.h

Discord contact: ravepossum

2024-03-23 23:38 UTC, lhearachel requested changes
Apologies in advance for the noise of "duplicate includes"; if you want to modify a previous commit and do a force-push to make that easier, feel free to do so.

2024-03-23 23:38 UTC, lhearachel commented on include/constants/heap.h
> +};
Should these also have a defining label?

Additionally, some conventions:
1. Always explicitly define the initial value.
2. Is `COUNT` meant to be the exclusive upper bound when looping over these values? e.g.:

```c
for (int i = 0; i < HEAP_BASE_ID_COUNT; i++) { /* stuff */ }
```

If so, our convention is that such values should be labeled `MAX`, as it represents a bound and not a total count of values.

2024-03-23 23:38 UTC, lhearachel commented on include/savedata.h
> +typedef struct {
Convention in the project is to specify a name for structs such that a user can choose whether they want to use `struct StructName` or `StructName` as a type-definition. The names can be identical (and, honestly, should be).

2024-03-23 23:38 UTC, lhearachel commented on include/savedata.h
> +typedef struct SaveData SaveData;
Superfluous typedef

2024-03-23 23:38 UTC, lhearachel commented on include/savedata.h
> +SaveData* InitializeSaveData(void);
`SaveData_Init`

2024-03-23 23:38 UTC, lhearachel commented on src/overlay005/ov5_021E1D20.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay059/ov59_021D2B44.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay057/ov57_021D0F30.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay061/ov61_0222AE60.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay062/ov62_02248408.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay097/ov97_0222AE60.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay097/ov97_02230410.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay097/ov97_02232054.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay097/ov97_02233B18.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/overlay097/ov97_02237694.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/party.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/poffin.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/party.c
> +    v0 = (Party *)SaveData_SaveTable(param0, 2);
Does the following match?

```suggestion
    return SaveData_SaveTable(param0, 2);
```

2024-03-23 23:38 UTC, lhearachel commented on src/poketch_data.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02014D38.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202440C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02025CB0.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02025E08.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202602C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02026150.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_020261E4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202631C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_020277A4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02027F84.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02028124.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202854C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_020298BC.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202ACE0.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202B37C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202B604.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202C7FC.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202C858.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202C9F4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202CC64.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202CC64.c
> +    return (ChatotCry *)SaveData_SaveTable(param0, 22);
Is this cast necessary?

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202CD50.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202D05C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202D778.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202D7A8.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202DA40.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202DAB4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202E840.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202F108.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202F1D4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0202FF4C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02030108.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_020302D0.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02030494.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0203061C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02030880.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02030A80.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02030CE8.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02030EA4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_020366A0.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02038ED4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0203A6DC.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0203D1B8.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0204CA84.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0204F13C.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_020507CC.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0206CCB0.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0207D3B8.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_02099DFC.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/unk_0209A2C4.c
> +#include "savedata.h"
Duplicate include

2024-03-23 23:38 UTC, lhearachel commented on src/savedata.c
> +    int sectorIndex, unused;
Is `unused` not stripped by the compiler? Does it not match if you remove the extraneous var?

Additionally, can you move `sectorIndex` further down?

2024-03-23 23:38 UTC, lhearachel commented on src/savedata.c
>          }
Unnecessary scope-block

2024-03-23 23:38 UTC, lhearachel commented on src/savedata.c
>      }
Does this have to exist in an `else` block?

2024-03-23 23:38 UTC, lhearachel commented on src/savedata.c
> +    int saveResult;
If you can declare this alongside the definition, do so; we use C99-style for this project.

I won't point out the other instances in the file, just making a note of this one.

2024-03-23 23:38 UTC, lhearachel commented on src/savedata.c
> +    saveResult = sub_0202513C(saveData);
Continuation from the above:

```suggestion
    int saveResult = sub_0202513C(saveData);
```

2024-03-24 02:45 UTC, cbt6 commented on include/constants/heap.h
> +};
```suggestion
enum HeapId {
    HEAP_ID_SYSTEM = 0,
    HEAP_ID_SAVE,
    HEAP_ID_DEBUG,
    HEAP_ID_APPLICATION,

    HEAP_ID_BATTLE = 5,
};
```

2024-03-24 02:53 UTC, cbt6 commented on include/constants/savedata/save_table.h
> +#endif // POKEPLATINUM_CONSTANTS_SAVE_TABLE_H
Add newline to EOF (and for all other new files)

2024-03-24 13:54 UTC, ravepossum commented
All the feedback from those reviews should be addressed now.

2024-03-24 21:36 UTC, lhearachel approved these changes

2024-03-24 21:36 UTC, merged