Decompile zukan_data NARC
pret/pokeplatinum pull request #263
Opened 2024-08-31 20:18 UTC by h2o-DS

Extracted data from application/zukanlist/zkn_data/zukan_list.narc

Individual pokemon data was appended to their data.json file

Body shapes were added as an enum in consts.pokemon

A make.py script was added to tool/scripts

Corresponding meson files were changed

prebuilt narc was deleted

2024-08-31 20:57 UTC, adrienntindall commented
zukan translates to pokedex, I forget how much of that is able to be translated file name wise but you should incorporate where you can

2024-08-31 21:06 UTC, lhearachel commented
> zukan translates to pokedex, I forget how much of that is able to be translated file name wise but you should incorporate where you can

Everything except for the final NARC name can be translated, essentially

2024-08-31 21:17 UTC, h2o-DS commented
I only used zukan in reference to filenames, like how shinzukan and pl_pokezukan are currently implemented.

I don't love the data.json variable names I came up with though, so if you have a better idea than "trainer_scale_f" let me know. Maybe they should be in a "pokedex_data" list or something so their application is more obvious.

2024-08-31 21:20 UTC, lhearachel commented
> `pokedex_data`

I think this would be fine. I also wouldn't shy away from using names that are descriptive as possible, in general. The more obvious data files are to end users, the better.

2024-09-22 01:32 UTC, lhearachel requested changes

2024-09-22 01:32 UTC, lhearachel commented on src/pokedex_data_index.c
> +}
**suggestion:** Give `param0` a name, and also document names for these message banks.

2024-09-22 01:32 UTC, lhearachel commented on src/pokedex_data_index.c
> +static u32 height_message_bank_index = 709;
**polish:** The rest of the repo typically:

1. Uses `camelCase`.
2. Prefixes static data symbols with `s`, e.g. `sWeightMessageBankIndex`.

2024-09-22 01:32 UTC, lhearachel commented on src/pokedex_heightweight.c
> +    height = sub_0200723C(pokedex_data_narc, 0, 0, param1, 0);
**polish:** Prefer declaration+definition in a single statement where possible.

2024-09-22 01:32 UTC, lhearachel commented on res/pokemon/abomasnow/data.json
> +        "category": "Frost Tree Pok\u00e9mon"
**polish:** Can these not be encoded using UTF-8 encoding on the files?

2024-09-22 01:32 UTC, lhearachel commented on res/pokemon/abomasnow/data.json
> +        "entry_text": "They appear when the snow flowers\\nbloom. When the petals fall, they\\nretreat to places unknown again.",
**question:** Do `\n` characters need to be double-escaped?

2024-09-25 18:28 UTC, lhearachel approved these changes

2024-09-25 18:28 UTC, merged