Document GameOptions struct + management code
pret/pokeplatinum pull request #6
Opened 2023-02-19 22:59 UTC by lhearachel

2023-04-03 23:20 UTC, luckytyphlosion requested changes

2023-04-03 23:20 UTC, luckytyphlosion commented on src/game_options.c
> +        default:                    return 1;
return statements should be on new line indented

2023-04-03 23:20 UTC, luckytyphlosion commented on src/game_options.c
> +    options->frameStyle     = FRAMESTYLE_01;
do not align

2023-04-03 23:20 UTC, luckytyphlosion commented on src/game_options.c
> +void GameOptions_SetTextSpeed (GameOptions * options, TextSpeed newVal)
actually didn't realize these were enums, they should say e.g. `enum TextSpeed` (do this for all)

2023-04-03 23:20 UTC, luckytyphlosion commented on include/game_options.h
> +} TextSpeed;
convert to non-typedef (do for all enums used)

2023-04-03 23:20 UTC, luckytyphlosion commented on include/struct_defs/game_options.h
> +    u16 textSpeed      : 4;     ///< Controls the speed at which text renders
Do not align between textSpeed and colon (do for all instances)

2023-04-03 23:20 UTC, luckytyphlosion commented on include/struct_defs/game_options.h
> +    u16 _padding       : 1;     ///< Padding alignment to 16 bits.
Do not prefix with `_` (names prefixed with `_` are reserved under C standard)

2023-04-03 23:20 UTC, luckytyphlosion commented on include/struct_defs/game_options.h
> +    u16 audioMode      : 2;     ///< Controls the method by which audio is
Is it possible to use the enums here? Don't remember if possible to set enum type, but don't bother if not matching

2023-04-03 23:20 UTC, luckytyphlosion commented on include/struct_defs/game_options.h
> +#ifndef POKEPLATINUM_STRUCT_GAME_OPTIONS_H
Move this stuff in the same file as game_options.h (do not use struct_defs, that's a temp folder that originated from the automated struct splitting)

2023-04-03 23:20 UTC, luckytyphlosion commented on src/game_options.c
> +    TextSpeed rawTextSpeedValue = GameOptions_GetTextSpeed(options);
Maybe think of better terminology (need to differentiate between textSpeed enum value (FAST/MID/SLOW) and text speed delay value)

2023-04-03 23:20 UTC, luckytyphlosion commented on src/game_options.c
> +    TextSpeed rawTextSpeedValue = GameOptions_GetTextSpeed(options);
LetterDelay is probably a better term here, or even just GetTextSpeedDelay (so rename `rawTextSpeedValue ` to `textSpeed` and function name to either `GameOptions_GetTextSpeedLetterDelay` or `GameOptions_GetTextSpeedDelay`)

2023-04-03 23:20 UTC, luckytyphlosion commented on src/game_options.c
> +void GameOptions_UpdateGlobalButtonMode (UnkStruct_021C0794 * saveData, ButtonMode newButtonMode)
Do we know if this is `newButtonMode` for a fact, even though `options->buttonMode` isn't set?

2023-10-26 00:59 UTC, PikalaxALT commented
Is this PR abandoned?

2023-10-26 00:59 UTC, closed without merging